// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_doctor.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ZYt5_17HjQeerKzbqg4L29fHggMA1WI',
    appId: '1:410142551302:web:ee17a467f63ac6247e8287',
    messagingSenderId: '410142551302',
    projectId: 'doctorapp-7f7e1',
    authDomain: 'doctorapp-7f7e1.firebaseapp.com',
    storageBucket: 'doctorapp-7f7e1.firebasestorage.app',
    measurementId: 'G-GX035C7528',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJCfOVUBbK370U7TJlyxmdgca27eRMHic',
    appId: '1:410142551302:android:150d6e7038577f347e8287',
    messagingSenderId: '410142551302',
    projectId: 'doctorapp-7f7e1',
    storageBucket: 'doctorapp-7f7e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0LA4jCcEBBdgs7fT3jbkoCC19MDMXl0M',
    appId: '1:410142551302:ios:e80c67a246cef02b7e8287',
    messagingSenderId: '410142551302',
    projectId: 'doctorapp-7f7e1',
    storageBucket: 'doctorapp-7f7e1.firebasestorage.app',
    iosBundleId: 'com.sagha.doctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0LA4jCcEBBdgs7fT3jbkoCC19MDMXl0M',
    appId: '1:410142551302:ios:424626404307cbc57e8287',
    messagingSenderId: '410142551302',
    projectId: 'doctorapp-7f7e1',
    storageBucket: 'doctorapp-7f7e1.firebasestorage.app',
    iosBundleId: 'com.healthcare.doctorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9ZYt5_17HjQeerKzbqg4L29fHggMA1WI',
    appId: '1:410142551302:web:d7dd548fa91904547e8287',
    messagingSenderId: '410142551302',
    projectId: 'doctorapp-7f7e1',
    authDomain: 'doctorapp-7f7e1.firebaseapp.com',
    storageBucket: 'doctorapp-7f7e1.firebasestorage.app',
    measurementId: 'G-Y5GKYKN19J',
  );

}